version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: booking_pg
    environment:
      POSTGRES_DB: booking_api
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking_user -d booking_api"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
